<?php
/**
 * @file
 * Code for the ottawa_toggle_block feature.
 */

include_once 'ottawa_toggle_block.features.inc';


/**
 * Implements hook_entity_info_alter().
 */
function ottawa_toggle_block_entity_info_alter(&$entity_info) {
    if ( isset($entity_info['bean']) ) {
        $entity_info['bean']['view modes']['toggle_icons'] = array(
            'label' => t('Toggle Group Icons'),
            'custom settings' => TRUE,
        );
    }
}

/**
* Implements hook_library().
*/
function ottawa_toggle_block_library() {
  $libraries['ottawa_toggle_block'] = array(
    'title' => 'Ottawa toogle block CSS library.',
    'version' => '1.0',
    'css' => array(
      drupal_get_path('module', 'ottawa_toggle_block') . '/css/ottawa_toggle_block.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
  );
  return $libraries;
}

/**
 * Implements template_preprocess_entity().
 *
 * @param array $var a keyed array with the entity data and meta data.
 */
function ottawa_toggle_block_preprocess_entity(&$var) {
    if ($var['entity_type'] == 'bean' && $var['elements']['#bundle'] == 'toggle_block') {
        $bean = $var['bean'];
        // Hide B content fields to display only A content fields.
        if( $bean->field_block_state[LANGUAGE_NONE][0]['value'] == 1 ) {
            unset( $var['content']['field_b_title'] );
            unset( $var['content']['field_b_body'] );
            unset( $var['content']['field__b_icon'] );
            unset( $var['content']['field__b_label'] );
        }
        // Hide A content fields to display only B content fields.
        else {
            unset( $var['content']['title_field'] );
            unset( $var['content']['field_a_body'] );
            unset( $var['content']['field__a_icon'] );
            unset( $var['content']['field__a_label'] );
        }

        // Load the CSS library for the Ottawa Toggle Block (mostly used for the group block)
        drupal_add_library('ottawa_toggle_block', 'ottawa_toggle_block');
    }
}

/**
 * Implements template_block_preprocess_block().
 *
 * @param array $variables a keyed array with they block data for the toggle bean.
 */
/*
function ottawa_toggle_block_preprocess_block(&$variables) {
  if( isset($variables['elements']['bean']) ) {
    foreach( $variables['elements']['bean'] as $key => $bean ) {
      if( is_array( $bean ) ) {
        if( isset($bean['#entity_type']) && isset($bean['#bundle']) ) {
          if( $bean['#entity_type'] == 'bean' && $bean['#bundle'] == 'toggle_block' ) {
            if( $bean['#entity']->field_block_state[LANGUAGE_NONE][0]['value'] == '0' ) {
              $variables['block']->subject = $bean['field_b_title'][0]['#markup'];
            }
          }
        }
      }
    }
  }
}
*/